// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailVerificationToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

type RefreshToken struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	TokenHash       string             `json:"token_hash"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	ReplacedByToken pgtype.UUID        `json:"replaced_by_token"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	Username      string             `json:"username"`
	PasswordHash  string             `json:"password_hash"`
	Name          string             `json:"name"`
	MobileNumber  pgtype.Text        `json:"mobile_number"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
	PlanID        pgtype.Int8        `json:"plan_id"`
	Roles         pgtype.Int8        `json:"roles"`
	EmailVerified bool               `json:"email_verified"`
	IsBlocked     bool               `json:"is_blocked"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
	Country       pgtype.Text        `json:"country"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Timezone      pgtype.Text        `json:"timezone"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}
