// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContact = `-- name: CreateContact :one


INSERT INTO contacts (
    user_id,
    display_name,
    first_name,
    surname,
    note,
    source
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, display_name, first_name, surname, note, source, created_at, updated_at, deleted_at
`

type CreateContactParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	DisplayName string      `json:"display_name"`
	FirstName   pgtype.Text `json:"first_name"`
	Surname     pgtype.Text `json:"surname"`
	Note        pgtype.Text `json:"note"`
	Source      string      `json:"source"`
}

// SQLC queries for contact management : contacts domain
// POST /contacts
func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.UserID,
		arg.DisplayName,
		arg.FirstName,
		arg.Surname,
		arg.Note,
		arg.Source,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.FirstName,
		&i.Surname,
		&i.Note,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one

INSERT INTO email_verification_tokens (
    user_id,
    token,
    expires_at
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, token, expires_at, created_at, used_at
`

type CreateEmailVerificationTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// SQLC queries for email verification tokens
func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one

INSERT INTO refresh_tokens (
    user_id,
    token_hash,
    expires_at
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, token_hash, expires_at, created_at, revoked_at, replaced_by_token
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// SQLC queries for refresh tokens
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ReplacedByToken,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    username,
    password_hash,
    name
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, email, username, password_hash, name, mobile_number, avatar_url, plan_id, roles, email_verified, is_blocked, last_login_at, country, created_at, updated_at, timezone, deleted_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
}

// SQLC queries for user management : auth domain
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Name,
		&i.MobileNumber,
		&i.AvatarUrl,
		&i.PlanID,
		&i.Roles,
		&i.EmailVerified,
		&i.IsBlocked,
		&i.LastLoginAt,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.DeletedAt,
	)
	return i, err
}

const deleteEmailVerificationToken = `-- name: DeleteEmailVerificationToken :exec
DELETE FROM email_verification_tokens
WHERE id = $1
`

func (q *Queries) DeleteEmailVerificationToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationToken, id)
	return err
}

const getContactByID = `-- name: GetContactByID :one

SELECT id, user_id, display_name, first_name, surname, note, source, created_at, updated_at, deleted_at
FROM contacts
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type GetContactByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// GET /contacts/{id}
func (q *Queries) GetContactByID(ctx context.Context, arg GetContactByIDParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactByID, arg.ID, arg.UserID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.FirstName,
		&i.Surname,
		&i.Note,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEmailVerificationToken = `-- name: GetEmailVerificationToken :one
SELECT id, user_id, token, expires_at, created_at, used_at
FROM email_verification_tokens
WHERE token = $1
`

func (q *Queries) GetEmailVerificationToken(ctx context.Context, token string) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationToken, token)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, created_at, revoked_at, replaced_by_token
FROM refresh_tokens
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ReplacedByToken,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password_hash, name, mobile_number, avatar_url, plan_id, roles, email_verified, is_blocked, last_login_at, country, created_at, updated_at, timezone, deleted_at
FROM users
WHERE email = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Name,
		&i.MobileNumber,
		&i.AvatarUrl,
		&i.PlanID,
		&i.Roles,
		&i.EmailVerified,
		&i.IsBlocked,
		&i.LastLoginAt,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmailOrUsername = `-- name: GetUserByEmailOrUsername :one
SELECT id, email, username, password_hash, name, mobile_number, avatar_url, plan_id, roles, email_verified, is_blocked, last_login_at, country, created_at, updated_at, timezone, deleted_at
FROM users
WHERE (email = $1 OR username = $1)
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByEmailOrUsername(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailOrUsername, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Name,
		&i.MobileNumber,
		&i.AvatarUrl,
		&i.PlanID,
		&i.Roles,
		&i.EmailVerified,
		&i.IsBlocked,
		&i.LastLoginAt,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password_hash, name, mobile_number, avatar_url, plan_id, roles, email_verified, is_blocked, last_login_at, country, created_at, updated_at, timezone, deleted_at
FROM users
WHERE username = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Name,
		&i.MobileNumber,
		&i.AvatarUrl,
		&i.PlanID,
		&i.Roles,
		&i.EmailVerified,
		&i.IsBlocked,
		&i.LastLoginAt,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.DeletedAt,
	)
	return i, err
}

const listContactsForUser = `-- name: ListContactsForUser :many

SELECT id, user_id, display_name, first_name, surname, note, source, created_at, updated_at, deleted_at
FROM contacts
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY display_name ASC
`

// GET /contacts?limit=&offset=
func (q *Queries) ListContactsForUser(ctx context.Context, userID pgtype.UUID) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContactsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.FirstName,
			&i.Surname,
			&i.Note,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsForUserWithDetails = `-- name: ListContactsForUserWithDetails :many
SELECT
	c.id,
	c.display_name,
	c.first_name,
	c.surname,
	c.note,
	c.source,
	COALESCE(
		json_agg(
			distinct jsonb_build_object(
			'label', p.label,
			'number', p.number,
			'isPrimary', p.is_primary
			)
		) filter (where p.id is not null)
	, '[]'::json) as phone_numbers,
	COALESCE(
		json_agg(
			distinct jsonb_build_object(
			'label', e.label,
			'email', e.email,
			'isPrimary', e.is_primary
			)
		) filter (where e.id is not null)
	, '[]'::json) as emails
FROM contacts c
LEFT JOIN contact_phone_numbers p 
		ON p.contact_id = c.id 
		AND p.user_id = c.user_id 
LEFT JOIN contact_emails e 
		ON e.contact_id = c.id
		AND e.user_id = c.user_id 
WHERE c.user_id = $1
	and c.deleted_at is null
group by c.id, c.display_name, c.first_name, c.surname, c.note, c.source
order by c.first_name asc
`

type ListContactsForUserWithDetailsRow struct {
	ID           pgtype.UUID `json:"id"`
	DisplayName  string      `json:"display_name"`
	FirstName    pgtype.Text `json:"first_name"`
	Surname      pgtype.Text `json:"surname"`
	Note         pgtype.Text `json:"note"`
	Source       string      `json:"source"`
	PhoneNumbers interface{} `json:"phone_numbers"`
	Emails       interface{} `json:"emails"`
}

// GET /contacts with details
func (q *Queries) ListContactsForUserWithDetails(ctx context.Context, userID pgtype.UUID) ([]ListContactsForUserWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, listContactsForUserWithDetails, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactsForUserWithDetailsRow
	for rows.Next() {
		var i ListContactsForUserWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.FirstName,
			&i.Surname,
			&i.Note,
			&i.Source,
			&i.PhoneNumbers,
			&i.Emails,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailsForContact = `-- name: ListEmailsForContact :many
SELECT id, user_id, contact_id, label, email, normalized_email, is_primary, created_at, updated_at
FROM contact_emails
WHERE contact_id = $1
`

func (q *Queries) ListEmailsForContact(ctx context.Context, contactID pgtype.UUID) ([]ContactEmail, error) {
	rows, err := q.db.Query(ctx, listEmailsForContact, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactEmail
	for rows.Next() {
		var i ContactEmail
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContactID,
			&i.Label,
			&i.Email,
			&i.NormalizedEmail,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhonesForContact = `-- name: ListPhonesForContact :many
SELECT id, user_id, contact_id, label, number, normalized_number, is_primary, created_at, updated_at
FROM contact_phone_numbers
WHERE contact_id = $1
`

func (q *Queries) ListPhonesForContact(ctx context.Context, contactID pgtype.UUID) ([]ContactPhoneNumber, error) {
	rows, err := q.db.Query(ctx, listPhonesForContact, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactPhoneNumber
	for rows.Next() {
		var i ContactPhoneNumber
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContactID,
			&i.Label,
			&i.Number,
			&i.NormalizedNumber,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerificationTokenUsed = `-- name: MarkEmailVerificationTokenUsed :exec
UPDATE email_verification_tokens
SET used_at = now()
WHERE id = $1
`

func (q *Queries) MarkEmailVerificationTokenUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerificationTokenUsed, id)
	return err
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :exec
UPDATE users
SET email_verified = TRUE,
    updated_at     = now()
WHERE id = $1
`

func (q *Queries) MarkUserEmailVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markUserEmailVerified, id)
	return err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const upsertContactEmail = `-- name: UpsertContactEmail :one
INSERT INTO contact_emails(
  user_id,
  contact_id,
  email,
  label,
  normalized_email,
  is_primary
)
VALUES( $1, $2, $3, $4, $5, $6
) ON CONFLICT (user_id, normalized_email) DO UPDATE
SET 
  contact_id = EXCLUDED.contact_id,
  email = EXCLUDED.email,
  label = EXCLUDED.label,
  is_primary = EXCLUDED.is_primary,
  updated_at = now()
RETURNING id, user_id, contact_id, label, email, normalized_email, is_primary, created_at, updated_at
`

type UpsertContactEmailParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	ContactID       pgtype.UUID `json:"contact_id"`
	Email           string      `json:"email"`
	Label           pgtype.Text `json:"label"`
	NormalizedEmail string      `json:"normalized_email"`
	IsPrimary       bool        `json:"is_primary"`
}

func (q *Queries) UpsertContactEmail(ctx context.Context, arg UpsertContactEmailParams) (ContactEmail, error) {
	row := q.db.QueryRow(ctx, upsertContactEmail,
		arg.UserID,
		arg.ContactID,
		arg.Email,
		arg.Label,
		arg.NormalizedEmail,
		arg.IsPrimary,
	)
	var i ContactEmail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContactID,
		&i.Label,
		&i.Email,
		&i.NormalizedEmail,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertContactPhone = `-- name: UpsertContactPhone :one
INSERT INTO contact_phone_numbers(
  user_id,
  contact_id,
  number,
  label,
  normalized_number,
  is_primary
)
VALUES( $1, $2, $3, $4, $5, $6
)
ON CONFLICT (user_id, normalized_number) DO UPDATE
SET
  contact_id = EXCLUDED.contact_id,
  number = EXCLUDED.number,
  label = EXCLUDED.label,
  is_primary = EXCLUDED.is_primary,
  updated_at = now()
RETURNING id, user_id, contact_id, label, number, normalized_number, is_primary, created_at, updated_at
`

type UpsertContactPhoneParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	ContactID        pgtype.UUID `json:"contact_id"`
	Number           string      `json:"number"`
	Label            pgtype.Text `json:"label"`
	NormalizedNumber string      `json:"normalized_number"`
	IsPrimary        bool        `json:"is_primary"`
}

func (q *Queries) UpsertContactPhone(ctx context.Context, arg UpsertContactPhoneParams) (ContactPhoneNumber, error) {
	row := q.db.QueryRow(ctx, upsertContactPhone,
		arg.UserID,
		arg.ContactID,
		arg.Number,
		arg.Label,
		arg.NormalizedNumber,
		arg.IsPrimary,
	)
	var i ContactPhoneNumber
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContactID,
		&i.Label,
		&i.Number,
		&i.NormalizedNumber,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
